package com.autoreason.setmincheck.setobjects;

import java.util.Set;

/**
 * A class to represent a {@link Set} together with its representation form
 * generated by {@link SetConverter#convertSet}.
 *
 * @param <R> The data type for the set representation (e.g. long[])
 */
public class SetRepresent<R> {
	/**
	 * A specific representation of a {@link Set} for simpler processing
	 */
	public R setRepresentation;

	/**
	 * The original {@link Set} used to create the {@link #setRepresentation}
	 */
	public Set<?> originalSet;

}
